image: ubuntu:18.04

before_script:
  - apt-get update
  - apt-get install -y gcc g++
  - apt-get install --yes cmake

compile:
  script:
    # Compile our app with cmake
    - export CC=gcc-7
    - export CXX=g++-7
    - cmake --version
    - cmake CMakeLists.txt
    - make

  # Save the compiled output from the above for downloading via GitLab and in Gitlab 8.6 to use in future build steps
  artifacts:
    paths:
      - TestedGraph
      - UnitTests

test:
  script:
    - ./UnitTests

run:
  script:
    - ./TestedGraph