name: Build project

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          run_tests: ON
          unit_test_build: -Dtest=ON

      - name: List
        run: ls -al /home/runner/work/testci/testci/build

      - name: Run
        run: /home/runner/work/testci/testci/build/UnitTests